spring:
  application:
    name: rockville-auth
  datasource:
    url: jdbc:mysql://localhost/rockville-auth
    username: root
    password: Bryce@27923
    hikari:
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  security:
    user:
      name: rockville
      password: rockville
server:
  port: 8000
  servlet:
    context-path: /auth