spring:
  application:
    name: rockville-auth
  datasource:
#    url: jdbc:mysql://localhost/rockville-auth
#    username: root
#    password: Bryce@27923
    url: jdbc:mysql://ec2-rv-cms.c5u8qw4iyyzb.ap-southeast-1.rds.amazonaws.com/rockville-auth
    username: root
    password: Bryce27923
    hikari:
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: rockville
      password: rockville
  sleuth:
    enabled: true
    sampler:
      percentage: 1
    zipkin:
      enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

server:
  port: 8000
  servlet:
    context-path: /auth

aws:
  accessKey: AKIATCKANC3CL5XHMJHY
  secretKey: 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


jwt:
  secret: d4r4g4lguw3b4ppjwts3cr3tt0kend4r4g4lguw3b4ppjwts3cr3tt0kend4r4g4lguw3b4ppjwts3cr3tt0ken
management:
  appoptics:
    metrics:
      export:
        enabled: false

