spring:
  application:
    name: rockville-auth
  datasource:
    url: jdbc:mysql://localhost/rockville-auth
    username: root
    password: Bryce@27923
    hikari:
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: rockville
      password: rockville
server:
  port: 8000
  servlet:
    context-path: /auth

aws:
  accessKey: AKIATCKANC3CL5XHMJHY
  secretKey: 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

jwt:
  secret: d4r4g4lguw3b4ppjwts3cr3tt0kend4r4g4lguw3b4ppjwts3cr3tt0kend4r4g4lguw3b4ppjwts3cr3tt0ken